FRAP_frame: 4
frame_actualization: 10
frame_pre_bleach:
- 0
- 1
- 2
- 3
- 4
- 249
im_path: /Volumes/tungsten/scratch/ggiorget/nessim/microscopy_data/FRAP_Rad21_halo/20240116_FRAP_NIPBL_FKBP/20240116_FRAP_NIPBL_FKBP_Rad21_Halo_561_30_LP_2_conf561Triple-LP-FRAP.ome.tf2
name_of_experiment: 20240116_NIPBL_FKBP_nodtag_30_LP_2
radius_bleach_spot: 7
radius_unbleach_spot: 5
save_path: /Users/louaness/Documents/cohesin_residence_time/runs/20240116_NIPBL_FKBP_nodtag_30_LP_2
size_of_bbox_zoom: 100
