FRAP_frame: 4
frame_actualization: 5
frame_pre_bleach:
- 0
- 1
- 2
- 3
- 4
- 249
im_path:#Path to the image .ome.tf2 file
name_of_experiment: 20240426_FRAP_WAPL_AID_noaux
radius_bleach_spot: 7
radius_unbleach_spot: 5
save_path: /Users/louaness/Documents/cohesin_residence_time/runs/20240426_FRAP_WAPL_AID_noaux
size_of_bbox_zoom: 100
