name: cohesin_residence_time
channels:
  - conda-forge
dependencies:
  - arrow
  - bioformats_jar
  - ca-certificates
  - cloudpickle
  - colorama
  - comm
  - contourpy
  - dask
  - dask-core
  - dav1d
  - debugpy
  - decorator
  - docformatter
  - docutils
  - entrypoints
  - ffmpeg
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - imagecodecs
  - imageio
  - imageio-ffmpeg
  - imagesize
  - importlib-metadata
  - importlib-resources
  - importlib_metadata
  - importlib_resources
  - iprogress
  - ipycanvas
  - ipyevents
  - ipykernel
  - ipython
  - ipywidgets
  - isoduration
  - joblib
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - lazy_loader
  - matplotlib
  - networkx
  - notebook
  - numpy
  - ome-types
  - openssl
  - pandas
  - pillow
  - pint
  - pip
  - pre-commit
  - psutil
  - pyarrow
  - python
  - qtconsole-base
  - qtpy
  - questionary
  - requests
  - resource_backed_dask_array
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - sphinx
  - stackview
  - statsmodels
  - tifffile
  - tqdm
  - wheel
  - xarray
  - xorg-libxau
  - xorg-libxdmcp
  - yaml
  - zarr